# Generated by Django 5.1.7 on 2025-04-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_linguagemprogramacao_rename_salary_jobpost_salario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='oportunidades_crescimento',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='responsabilidades',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='beneficios',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='informacoes_empresa',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='requisitos',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
