# Generated by Django 5.1.7 on 2025-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_remove_jobpost_oportunidades_crescimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguagemprogramacao',
            name='nome',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('C#', 'C#'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin')], max_length=50),
        ),
    ]
