# Generated by Django 5.1.7 on 2025-04-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_alter_linguagemprogramacao_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='tecnologias_usadas',
            new_name='area_desenvolvimento',
        ),
    ]
